#!/bin/bash
# lets user use short-hand for conman sj  and  conman "setsym 2 sj " commands.
#     sj computer#jobStream          # for today's schedules
# or  sj computer#jobStream 2        # for setsym 2 schedule
# or  sj 2 computer#jobStream        # likewise, for setsym 2 schedule
# or  sj  computer#jobStream 2 stdl        # likewise, for setsym 2 schedule
# or  sj  computer#jobStream  stdl  2      # likewise, for setsym 2 schedule
#
# Script also filters out the ibm BS that we do not want to see, letting us see
# the output better.

args=()
for a in "$@" 
do 
   if [[ $a =~ [^[:digit:]] ]]; then         # not a number
		 args+=($a)
   elif [ -z "$ssd" ]; then
         ssd="setsym $a &"
   else
		 echo Too many numbers. Dropping $a.
   fi
done

conman \"$ssd ss ${args[@]}\" 2>/dev/null | grep -ve "^Scheduled for" -ve "^Workstation " -ve "(Est)"


# echo "conman \"$ssd sj ${args[@]}\" 2>/dev/null" | grep -ve "^Scheduled for" -ve "^Workstation " -ve "(Est)"
